version: '2.4'
services:

  minio0:
    image: minio/minio:RELEASE.2020-02-27T00-23-05Z
    environment:
    - MINIO_ACCESS_KEY=something
    - MINIO_SECRET_KEY=nonsecret
    command:
    - server
    - /data
    expose:
    - 9000
    mem_limit: 20000000

  app0:
    depends_on:
    - minio0
    build:
      context: .
    command:
    - --host=minio0:9000
    - --secure=false
    - --accesskey=something
    - --secretkey=nonsecret
    - --inbox=bucket.write
    - --archive=bucket.read
    mem_limit: 20000000

  sut:
    depends_on:
    - minio0
    - app0
    image: minio/mc:RELEASE.2020-02-25T18-10-03Z
    entrypoint:
    - /bin/sh
    - -cx
    command:
    - |
      mc config host add minio0 http://minio0:9000

      echo "Test1" > test1.txt
      mc --no-color cp test1.txt minio0/bucket.write/
      sleep 1
      mc --no-color stat minio0/buckeet.read/$$(sha256sum test1.txt | cut -d' ' -f1).txt

      # TODO X-Custom-Header

      # TODO Content-Disposition

      # TODO dir sharding option 0-3
