version: '2.4'
services:

  minio0:
    image: docker.io/minio/minio:RELEASE.2021-11-09T03-21-45Z@sha256:e5048d2a503e0f2a18de9752831a8bf27a3e8a0eeebe35a87b9c56f967a9ef85
    command:
    - server
    - /data
    expose:
    - 9000
    mem_limit: 40000000

  app0:
    depends_on:
    - minio0
    build:
      context: .
    expose:
    - 2112
    command:
    - --host=minio0:9000
    - --secure=false
    - --accesskey=minioadmin
    - --secretkey=minioadmin
    - --inbox=bucket.write
    - --archive=bucket.read
    #- --trace=true
    mem_limit: 20000000

  sut:
    depends_on:
    - minio0
    - app0
    build: ./tests
    environment:
    - DEBUG=true
    - TESTS_DISABLED=${TESTS_DISABLED:-true}
    - MINIO_ACCESS_KEY=minioadmin
    - MINIO_SECRET_KEY=minioadmin
    entrypoint:
    - all.sh
