version: '2.4'
services:
  # Overrides for docker-compose.test.yml

  app0:
    command:
    - --host=minio0:9000
    - --secure=false
    - --accesskey=minioadmin
    - --secretkey=minioadmin
    - --inbox=bucket.write
    - --archive=bucket.read
    - --batch
    - --batchmetrics
    deploy:
      restart_policy:
        condition: any
        delay: 3s
