version: '2.4'
services:

  minio0:
    image: minio/minio:RELEASE.2020-02-27T00-23-05Z
    command:
    - server
    - /data
    expose:
    - 9000
    mem_limit: 20000000

  app0:
    depends_on:
    - minio0
    build:
      context: .
    command:
    - --host=minio0:9000
    - --secure=false
    - --accesskey=minioadmin
    - --secretkey=minioadmin
    - --inbox=bucket.write
    - --archive=bucket.read
    mem_limit: 20000000

  sut:
    depends_on:
    - minio0
    - app0
    build: ./tests
    environment:
    - DEBUG=true
    - MINIO_ACCESS_KEY=minioadmin
    - MINIO_SECRET_KEY=minioadmin
    entrypoint:
    - basic-flow.sh
