# yaml-language-server: $schema=https://raw.githubusercontent.com/docker/cli/v24.0.4/cli/compose/schema/data/config_schema_v3.9.json
version: '3.9'
services:
  # Overrides for docker-compose.test.yml

  app0:
    command:
    - --host=minio0:9000
    - --secure=false
    - --accesskey=minioadmin
    - --secretkey=minioadmin
    - --inbox=bucket.write
    - --archive=bucket.read
    - --batch
    - --batchmetrics
    deploy:
      restart_policy:
        condition: any
        delay: 3s

  sut:
    environment:
    - DEBUG=true
    - TESTS_DISABLED=${TESTS_DISABLED:-true}
    - ACCEPTABLE_TRANSFER_DELAY=${ACCEPTABLE_TRANSFER_DELAY:-20}
    - MINIO_ACCESS_KEY=minioadmin
    - MINIO_SECRET_KEY=minioadmin
