# yaml-language-server: $schema=https://raw.githubusercontent.com/docker/cli/v24.0.4/cli/compose/schema/data/config_schema_v3.9.json
version: '3.9'
services:

  minio0:
    image: docker.io/minio/minio:RELEASE.2023-10-16T04-13-43Z
    command:
    - server
    - /data
    environment:
      MINIO_PROMETHEUS_AUTH_TYPE: public
    expose:
    - 9000
    deploy:
      resources:
        limits:
          memory: 60M

  app0:
    depends_on:
    - minio0
    build:
      context: .
    expose:
    - 2112
    command:
    - --host=minio0:9000
    - --secure=false
    - --accesskey=minioadmin
    - --secretkey=minioadmin
    - --inbox=bucket.write
    - --archive=bucket.read
    - --dropempty
    #- --trace=true
    deploy:
      resources:
        limits:
          memory: 20M

  sut:
    depends_on:
    - minio0
    - app0
    build: ./tests
    environment:
    - DEBUG=true
    - TESTS_DISABLED=${TESTS_DISABLED:-true}
    - ACCEPTABLE_TRANSFER_DELAY=${ACCEPTABLE_TRANSFER_DELAY:-3}
    - MINIO_ACCESS_KEY=minioadmin
    - MINIO_SECRET_KEY=minioadmin
    entrypoint:
    - all.sh
